### ISSUE TITLE
string type converts to a pointer

### ISSUE THREAD

**Issue by pmazzini** [go-zookeeper/jute#19]
Why is the string type converted to a string pointer?

Example:

https://github.com/go-zookeeper/jute/blob/master/testdata/fixtures/zookeeper/data/id.go#L13

Reference:

https://github.com/go-zookeeper/jute/blob/master/generate/gogen/types.go#L135

**Comment by nemith** [comment]
When encoding on the wire there is a difference between an empty string and null.  I remember finding somewhere this is used in practice.

So essentially a way to state that it's optional.   The Getters should be able to help here.

**Comment by pmazzini** [comment]
The [jute docs](https://zookeeper.apache.org/doc/r3.4.11/api/org/apache/jute/package-summary.html) show that a `ustring` will end up being a `std::string` in C++, which is not nillable.

And the IDL does not allow specifying optional types like Thrift does.

>  I remember finding somewhere this is used in practice.

Do you remember where?

**Comment by nemith** [comment]
I think it was `ReconfigRequest`.  Currently the manual Go implementation uses []byte but in jute it is defined as ustring.    If i remember right an empty string for `joiningServers`, `leavingServiers` and `newMemeber` has a different operation. 

We can see what C++ does, but (again bad memory) I think Java set these to nil (which is 0xff, 0xff, 0xff, 0xff) and not a just length of 0x0.  Perhaps all that needs to happen is to send nil on a empty string?

**Comment by pmazzini** [comment]
> Perhaps all that needs to happen is to send nil on a empty string?

It looks like that is what the [Python library is doing]( 
https://github.com/python-zk/kazoo/blob/6b6ffe62a073d1ed5413c65c2d8ec94ea2fa1760/kazoo/protocol/serialization.py#L47).

Do you mind if I change the `ustring` to convert to `string` instead of `*string`?

**Comment by nemith** [comment]
Nope.  I am happy being wrong here.
